# Generated by Django 4.0.5 on 2022-07-03 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('content', models.CharField(help_text='The content of the tweet', max_length=280, verbose_name='Content')),
                ('public', models.BooleanField(default=True, help_text='Defines whether the tweet is public', verbose_name='Public')),
                ('likes', models.JSONField(default=list, help_text='List of users who liked the tweet', verbose_name='Likes')),
                ('retweets', models.IntegerField(default=0, help_text='The number of retweets', verbose_name='Retweets')),
                ('commented_retweets', models.IntegerField(default=0, help_text='The number of commented retweets', verbose_name='Commented Retweets')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the tweet was created', verbose_name='Created At')),
                ('author', models.ForeignKey(help_text='The author of the tweet', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Author')),
            ],
        ),
    ]
